### ISSUE TITLE
Auth login fails if password contains bang (!)

### ISSUE THREAD

**Issue by mm-gmbd** [electricimp/imp-central-impt#10] opened 2018-03-27 12:59 UTC
```
impt auth login -u username -w abc!@123

> bash !@123 not found
```

Looks like the command is interpreting the ! as the [bash bang operator](https://ss64.com/bash/bang.html).

**Comment by ppetrosh** [comment] 2018-04-10 00:31
@mm-gmbd the issue is not specific to the tool. The bank sign should be properly escaped or used inside single quotes in Lunux: https://stackoverflow.com/questions/27216951/how-to-escape-the-bang-character-in-linux-bash-shell

Unless you have any objections I tend to close it as not an issue...

**Comment by ppetrosh** [comment] 2018-04-10 16:18
Closing (while I remember). @mm-gmbd please feel free to reopen if you disagree.

**Closed** 2018-04-10 16:18 UTC

**Comment by mm-gmbd** [comment] 2018-04-10 17:04
@ppetrosh, thanks for looking into this, and I agree this is not a problem with impt. However, it may be nice to add a line warning against this in the README:

In README.md:

```
## Authentication ##

Calls to the impCentral API need to be authenticated. *impt* provides the [login command](./CommandsManual.md#auth-login) for this purpose. It can be used in either of two ways:

- Using an account identifier (an email address or a username) and password: `impt auth login --user <user_id> --pwd <password>`
  - NOTE: If your username or password contains certain special characters, such as the "!", you may need to wrap the `user_id` and `password` in single quotes to avoid [potential bash interpretation issues](https://ss64.com/bash/bang.html) (e.g. `impt auth login --user 'AUserId' --pwd 'A!Password'`)
- Using a [login key](#login-keys): `impt auth login --lk <login_key>`
```

GFM renders:

## Authentication ##

Calls to the impCentral API need to be authenticated. *impt* provides the [login command](./CommandsManual.md#auth-login) for this purpose. It can be used in either of two ways:

- Using an account identifier (an email address or a username) and password: `impt auth login --user <user_id> --pwd <password>`
  - NOTE: If your username or password contains certain special characters, such as the "!", you may need to wrap the `user_id` and `password` in single quotes to avoid [potential bash interpretation issues](https://ss64.com/bash/bang.html) (e.g. `impt auth login --user 'AUserId' --pwd 'A!Password'`)
- Using a [login key](#login-keys): `impt auth login --lk <login_key>`
